# <font color='red'><b>Bootstrap assignment</b> </font>

<b>There will be some functions that start with the word "grader" ex: grader_sampples(), grader_30().. etc, you should not change those function definition.

Every Grader function has to return True.</b>

<font color='blue'> <b>Importing packages</b> </font>

In [9]:
import numpy as np # importing numpy for numerical computation
from sklearn.datasets import load_boston # here we are using sklearn's boston dataset
from sklearn.metrics import mean_squared_error # importing mean_squared_error metric

In [10]:
boston = load_boston()
x=boston.data #independent variables
y=boston.target #target variable

In [11]:
x.shape

(506, 13)

In [12]:
x[:5]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00]])

## <font color='red'><b>Task 1</b></font>

<font color='red'> <b>Step - 1</b></font>

*  <font color='blue'><b>Creating samples</b></font><br>
    <b> Randomly create 30 samples from the whole boston data points</b>
    *  Creating each sample: Consider any random 303(60% of 506) data points from whole data set and then replicate any 203 points from the sampled points
    
     For better understanding of this procedure lets check this examples, assume we have 10 data points [1,2,3,4,5,6,7,8,9,10], first we take 6 data points randomly , consider we have selected [4, 5, 7, 8, 9, 3] now we will replicate 4 points from [4, 5, 7, 8, 9, 3], consder they are [5, 8, 3,7] so our final sample will be [4, 5, 7, 8, 9, 3, 5, 8, 3,7]
* <font color='blue'><b> Create 30 samples </b></font>
    *  Note that as a part of the Bagging when you are taking the random samples <b>make sure each of the sample will have different set of columns</b><br>
Ex: Assume we have 10 columns[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10] for the first sample we will select [3, 4, 5, 9, 1, 2] and for the second sample  [7, 9, 1, 4, 5, 6, 2] and so on...
Make sure each sample will have atleast 3 feautres/columns/attributes

<font color='red'><b>Step - 2 </b></font>

<font color='blue'><b>Building High Variance Models on each of the sample and finding train MSE value</b></font>

*  Build a regression trees on each of 30 samples.
*  Computed the predicted values of each data point(506 data points) in your corpus.
*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{30}\sum_{k=1}^{30}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$
*  Now calculate the $MSE =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$

<font color='red'> <b>Step - 3 </b></font>

*  <font color='blue'><b>Calculating the OOB score </b></font>

*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{k}\sum_{\text{k= model which was buit on samples not included } x^{i}}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$.
*  Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

# <font color='red'><b>Task 2</b></font>

*  <font color='blue'><b>Computing CI of OOB Score and Train MSE</b></font>
  *   Repeat Task 1 for 35 times, and for each iteration store the Train MSE and OOB score </li>
<li> After this we will have 35 Train MSE values and 35 OOB scores </li>
<li> using these 35 values (assume like a sample) find the confidence intravels of MSE and OOB Score </li>
<li> you need to report CI of MSE and CI of OOB Score </li>
<li> Note: Refer the Central_Limit_theorem.ipynb to check how to find the confidence intravel</li>
</ol>

# <font color='red'><b>Task 3</b></font>

*  <font color='blue'><b>Given a single query point predict the price of house.</b></font>

Consider xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60] 
Predict the house price for this point as mentioned in the step 2 of Task 1.

<br><br><br>

# <font color='blue'> <b>Task - 1</b></font>

<font color='blue'><b>Step - 1</b></font>

*  <font color='blue'> <b>Creating samples</b></font>

<font color='Orange'><b>Algorithm</b></font>

![alt text](https://i.imgur.com/BTVYXQ1.jpg/)

*  <font color='blue'><b> Write code for generating samples</b></font>

In [5]:
import random

def generate_sample(input_data,target_data):
  
  Selected_rows = np.random.choice(505,size=303,replace=False) # generate 303 random row
  Selected_rows = np.sort(Selected_rows)
  Selected_columns  = np.random.choice(13,size=13,replace=False)
  Selected_columns =  np.sort(Selected_columns)
  Repeated_rows = np.random.choice(Selected_rows,size=203,replace=False)# replicate 203 rows
  Repeated_rows = np.sort(Repeated_rows)
  sample_data = input_data[Selected_rows[:,None],Selected_columns]
  target_sample_data = target_data[Selected_rows]

  Replicated_sample_data = input_data[Repeated_rows[:,None],Selected_columns]
  Replicated_target_sample_data = target_data[Repeated_rows]

  final_sample_data = np.concatenate((sample_data,Replicated_sample_data))
  final_target_data = np.concatenate((target_sample_data, Replicated_target_sample_data))

  # generate oob rows
  oob_rows = np.array([i for i in range(0,506) if i not in Selected_rows])
  oob_data = input_data[oob_rows[:,None],Selected_columns]

  return final_sample_data,final_target_data,Selected_rows,Selected_columns,oob_data

list_input_data =[]
list_output_data =[]
list_selected_rows =[]
list_selected_columns =[]
list_oob_data =[]

for i in range(30):
  a,b,c,d,e = generate_sample(x,y)
  list_input_data.append(a)
  list_output_data.append(b)
  list_selected_rows.append(c)
  list_selected_columns.append(d)
  list_oob_data.append(e)

In [6]:
list_selected_columns[0].shape

(13,)

<font color='cyan'> <b>Grader function - 1 </b></font>

In [8]:
def grader_30(a):
    assert(len(a)==30 and len(a[0])==506)
    return True
grader_30(list_input_data)

True

<br>

<font color='red'><b>Step - 2 </b></font>

<font color='orange'><b>Flowchart for building tree</b></font>

![alt text](https://i.imgur.com/pcXfSmp.png)

*  <font color='blue'><b> Write code for building regression trees</b></font>

In [13]:

from sklearn.tree import DecisionTreeRegressor

def model_train_gen(input_data,output_data):
  models=[]

  for j in range(len(input_data)):

    regressor = DecisionTreeRegressor(max_depth = None)
    model = regressor.fit(input_data[j],output_data[j])
    models.append(model)
  return models

<font color='orange'><b>Flowchart for calculating MSE </b></font>

![alt text](https://i.imgur.com/sPEE618.png)

After getting predicted_y for each data point, we can use sklearns mean_squared_error to calculate the MSE between predicted_y and actual_y.

*  <font color='blue'><b> Write code for calculating MSE</b></font>

In [14]:
def mse_score_gen(x,models,selected_columns):
  y_pred_for_mse=[]

  for i in x:
    y_pred =[]

    for j in range(len(models)):
      y_pred.append(models[j].predict(i[selected_columns[j]].reshape(1,-1)))
    y_pred_for_mse.append(np.median(np.asarray(y_pred)))

  mse = mean_squared_error(y,np.asarray(y_pred_for_mse))


  
  return mse

<font color='blue'><b>Step - 3 </b></font>

<font color='orange'><b>Flowchart for calculating OOB score</b></font>

![alt text](https://i.imgur.com/95S5Mtm.png)

Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

*  <font color='blue'><b> Write code for calculating OOB score </b></font>

In [15]:
def oob_score_gen(x,models,selected_columns,selected_rows):
  y_pred_for_oob=[]

  for i in range(len(x)):
    a=x[i]
    y_pred =[]

    for j in range(len(models)):
      if i not in selected_rows[j]:
        y_pred.append(models[j].predict(a[selected_columns[j]].reshape(1,-1)))
    y_pred_for_oob.append(np.median(np.asarray(y_pred)))

  oob = mean_squared_error(y,np.asarray(y_pred_for_oob))

  
  return oob

# Execution of MSE and OOB score

In [16]:
models = model_train_gen(list_input_data,list_output_data)
mse = mse_score_gen(x,models,list_selected_columns)
print(mse)
oob = oob_score_gen(x,models,list_selected_columns,list_selected_rows)
print(oob)

0.1811264822134388
14.861082015810277


# <font color='blue'><b>Task 2</b></font>

In [17]:
MSE_arr =[]
OOB_arr =[]
list_input_data =[]
list_output_data =[]
list_selected_rows =[]
list_selected_columns =[]
list_oob_data =[]

for j in range(35):

  for i in range(30):
    o,p,q,r,s = generate_sample(x,y)
    list_input_data.append(o)
    list_output_data.append(p)
    list_selected_rows.append(q)
    list_selected_columns.append(r)
    list_oob_data.append(s)
  
  updated_models = model_train_gen(list_input_data,list_output_data)

  mse_val = mse_score_gen(x,updated_models, list_selected_columns)
  MSE_arr.append(mse_val)
  
  oob_val = oob_score_gen(x,updated_models,list_selected_columns,list_selected_rows)
  OOB_arr.append(oob_val)

print(len(MSE_arr))
print(len(OOB_arr))

35
35


In [18]:
MSE_arr

[0.4607262845849802,
 0.3356521739130434,
 0.23851778656126488,
 0.23851778656126488,
 0.23851778656126488,
 0.23567193675889334,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416,
 0.14958498023715416]

# MSE CI

In [19]:
np.percentile(MSE_arr, [2.5,  97.5])

array([0.14958498, 0.35441329])

# OOB CI

In [20]:
np.percentile(OOB_arr, [2.5,  97.5])

array([ 9.31243404, 11.57926803])

# <font color='blue'><b>Task 3</b></font>

<font color='orange'><b>Flowchart for Task 3</b></font>

<b>Hint: </b> We created 30 models by using 30 samples in TASK-1. Here, we need send query point "xq"  to 30 models and perform the regression on the output generated by 30 models.

![alt text](https://i.imgur.com/Y5cNhQk.png)

*  <font color='blue'><b> Write code for TASK 3 </b></font>

In [21]:
import numpy as np
xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60]
xq= np.array(xq).reshape(1,-1)
xq.shape

(1, 13)

In [22]:
def pred_price(xq,models,selected_columns):
  y_pred_price=[]

  for i in xq:
    y_pred =[]

    for j in range(len(models)):
      y_pred.append(models[j].predict(i[selected_columns[j]].reshape(1,-1)))
    y_pred_price.append(np.median(np.asarray(y_pred)))
 
  return y_pred_price

house_price = pred_price(xq,models,list_selected_columns)
print(house_price)

[18.5]


<br><br><br>