<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    #result=[[0,0,0],[0,0,0],[0,0,0]]
    result=[[0 for i in range(len(B[0]))] for j in range(len(A))]
    if(len(A[0])==len(B)):

      for i in range(len(A)):
          for j in range(len(B[0])):
             for k in range(len(B)):
                result[i][j]+=A[i][k]*B[k][j]
      for r in result:
        print (r)    
    else:
      return("NOT POSSIBLE")
A   = [[1,3,4],[2,5,8],[5,9,6]]
B   = [[1,0,0],[0,1,0],[0,0,1]]    
matrix_mul(A, B)

[1, 3, 4]
[2, 5, 8]
[5, 9, 6]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [3]:
import random
from bisect import bisect

A = [0,5,27,6,13,28,100,45,10,79]
A.sort()

def pick_a_number_from_list(A):
    cumsum = [sum(A[:i+1]) for i in range(len(A))] 
    out = []
    rnd = random.random()                     #Generate a number between 0 to 1 
    index = bisect(cumsum, rnd*cumsum[-1])  # it gives us the index of A 
    #print(index)
    out.append(A[index])
    return out

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number,end = " ")

sampling_based_on_magnitued()

[27] [27] [79] [79] [28] [13] [79] [45] [100] [100] [100] [28] [6] [79] [79] [79] [79] [100] [79] [79] [27] [28] [100] [79] [79] [100] [28] [79] [100] [100] [27] [79] [79] [100] [100] [27] [79] [45] [45] [100] [45] [79] [79] [45] [5] [5] [27] [45] [27] [27] [13] [79] [100] [79] [100] [100] [100] [10] [45] [79] [27] [27] [13] [79] [27] [79] [79] [100] [100] [45] [5] [13] [45] [45] [79] [79] [45] [6] [100] [79] [27] [79] [100] [28] [79] [79] [28] [79] [28] [45] [13] [27] [100] [28] [79] [28] [79] [28] [45] 

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [13]:
import re

String = '#2a$#b%c%561#'

def replace_digits(String):
    """Replace digits occurrance with symbol `#` and remove non digit
    characters with white space in given string

    Parameters
    ----------
    String: string


    Return
    ------
    res_string: string

    """

    res_string = ''
    
    matches = re.findall('[0-9]', String)
    matches_len = len(matches)
    
    if matches_len is not 0:
        res_string = '#'*matches_len
        
    return(res_string)
    

replace_digits(String)

'####'











































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 <h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [12]:

students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

max_marks = max(marks)

def check_data_sanity(list_i, list_ii):
    """Validate wether two list length are identical or not

    Parameters
    ----------
    list_i: list
    list_ii: list

    Return
    ------
        Boolean

    """
    
    return len(list_i) == len(list_ii)


def map_students_marks(students, marks):
    """Validate wether two list length are identical or not

    Parameters
    ----------
    students: list
        List of students
        
    marks: list
        Lsit of student's marks in `students` list

    Return
    ------
    mapped_entities: dict
        Individual student get mapped with obtained marks in exam

    """
    
    mapped_entities = dict(zip(students, marks))

    return mapped_entities


def display_dash_board(mapped_entities, max_marks, q1 = 0.25, q3 = 0.75):
    """Calculate
        1. Top 5 students
        2. Top bottom 5 students
        3. Students whose percentile between (0.25 to 0.75)

    Parameters
    ----------
    mapped_entities: dict
        Mapped students name with percentile

    max_marks: int
        Maximum marks obtained by individual student
        
    q1: float
        Interquartile A
        
    q3: flaot
        Interquartile B

    Return
    ------
        Top 5 students, Top bottom 5 students, Students whose percentile between (0.25 to 0.75)
    """
    
    sorted_res = sorted(mapped_entities, key = mapped_entities.get, reverse = True)
    
    # write code for computing top top 5 students
    top_5_students = sorted_res[:5]
    
    # write code for computing top least 5 students
    least_5_students = sorted_res[-1:-6:-1]
    
    # write code for computing top least 5 students
    students_within_25_and_75_dict = {
                                    key: mapped_entities[key]
                                    for key in mapped_entities
                                    if (mapped_entities[key] / max_marks > q1 and mapped_entities[key] / max_marks < q3)
                                }
    
    students_within_25_and_75 = sorted(students_within_25_and_75_dict, key = students_within_25_and_75_dict.get)


    return top_5_students, least_5_students, students_within_25_and_75


is_data_valid = False
is_data_valid = check_data_sanity(students, marks)

if is_data_valid:
    
    mapped_entities = map_students_marks(students, marks)

    top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(mapped_entities, max_marks)
    
    print(top_5_students)
    print(least_5_students)
    print(students_within_25_and_75)  

['student8', 'student10', 'student2', 'student5', 'student7']
['student3', 'student4', 'student9', 'student6', 'student1']
['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

def closest_points_to_p(S, P):
  SList=list(S)
  PList=list(P)
  dist=[]
  for i in range(0,len(SList)):
    numo=SList[i][0]*PList[0]+SList[i][1]*PList[1]
    deno1=math.sqrt(SList[i][0]*SList[i][0]+SList[i][1]*SList[i][1])
    deno2=math.sqrt(PList[0]*PList[0]+PList[1]*PList[1])
    deno=deno1*deno2
    d=math.acos(numo/deno)
    dist.append(d)
  distSort=[]
  for x in dist:
    distSort.append(x)
  distSort.sort()
  for i in range(0,5):
    for j in range(0,len(dist)):
        if (distSort[i]==dist[j]):
            print(tuple(SList[j]))
    

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)


(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    l=[]
    for i in range(len(line)):
        res=re.split('x|y', line[i]) # "Abhisheak is good boy" split(" ") -> ["Abhisheak"," ","is",} regex java,py -> string operation 1,+1,+0
        l.append(res)
#print(l)  # l=[['1', '+1', '+0'], ['1', '-1', '+0'], ['1', '+0', '-3'], ['0', '+1', '-0.5']]
    lineParse=[]
    for i in range(len(l)):
        #print("i=",i)
        #print("l[i]=",l[i])
        n=[]
        x=float(l[i][0])
        n.append(x)
        y=float(l[i][1])
        n.append(y)
        c=float(l[i][2])
        n.append(c)
        #print("X=",x, " y=",y," c=",c," n=",n)
        lineParse.append(n)
        #print("lineParse=",lineParse)
        #print(lineParse) # lineParse=[[1.0, 1.0, 0.0], [1.0, -1.0, 0.0], [1.0, 0.0, -3.0], [0.0, 1.0, -0.5]]

    for i in range(len(lineParse)):
        flagline=0
        flagred=0
        flagblue=0
        r1x=red[0][0] # l1=1,1,0   l2=1,-1,0   l3=1,0,-3    l4-> 0,1,-5
        r1y=red[0][1]
        b1x=blue[0][0]
        b1y=blue[0][1]
        r1=r1x*lineParse[i][0]+r1y*lineParse[i][1]+lineParse[i][2] # l1 -> 2    l2 ->0     l3-> -2    l4->.5
        b1=b1x*lineParse[i][0]+b1y*lineParse[i][1]+lineParse[i][2] # l1 -> -3   l2 ->-1    13->  1    l4-> -1.5
        if(r1>0):
            flagred=1
        elif(r1<0):
            flagred=-1
        if(b1>0):
            flagblue=1
        elif(b1<0):
            flagblue=-1
    
    #l1 fr->1 fb->-1 ->proceed
    #l2 fr->0 fb->-1 -> fail: any one flag->0 or two flags are equal
    #l3 fr->-1 fb->1 ->proceed
    #l4 fr->1 fb->-1 ->proceed
        
    #flag=red -> stop
    #flag g-> go
    #flag y-> watch
    
        if ((flagred==flagblue) or (flagred==0 or flagblue==0)):
            flagline=1
        #print("first if")
        else:
            for j in range(1,len(red)):
                flagred2=0
                rx=red[j][0] 
                ry=red[j][1]
                r=rx*lineParse[i][0]+ry*lineParse[i][1]+lineParse[i][2]
                if(r>0):
                    flagred2=1
                elif(r<0):
                    flagred2=-1
                if(flagred2!=flagred):
                    flagline=1
                    #print("Second red if")
                    break
            for j in range(1,len(blue)):
                flagblue2=0
                bx=blue[j][0] 
                by=blue[j][1]
                b=bx*lineParse[i][0]+by*lineParse[i][1]+lineParse[i][2]
                if(b>0):
                    flagblue2=1
                elif(b<0):
                    flagblue2=-1
                if(flagblue2!=flagblue):
                    flagline=1
                    #print("Second blue if")
                    break
        if(flagline==0):
            print("YES")
        else:
            print("No")

    
    return

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

i_am_the_one(Red, Blue, Lines)

YES
No
No
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [14]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import re

s = "80,_,_,_,_"

def curve_smoothing(s):
    """Filling the missing values in the string with specified formate

    Parameters
    ----------
    s: string

    Return
    ------
    join_string: string    
        string with specified formate
    """

    
    list_items = s.split(',')

    is_first = True
    last_num = 0

    placeholder_count = 0

    updated_items = []
    for index, item in enumerate(list_items):

        if item == '_':
            placeholder_count += 1
        else:

            parsed_item = float(item)

            """
            To handle first iteration of below input string patterns
                s = "40,_,_,_,60"
                (OR)
                s = "80,_,_,_,_"
                (OR)
                s = "2_,_,30,_,_,_,50,_,_"
            """
            if is_first and last_num == 0 and index == 0:
                placeholder_count += 1
                is_first, last_num = False, parsed_item


            elif is_first and last_num == 0:
                """
                To handle first iteration of below input string patterns
                    s = "_,_,_,60"
                    (OR)
                    s = "_,_,30,_,_,_,50,_,_"
                """                

                placeholder_count += 1

                val = parsed_item / placeholder_count
                updated_items.extend( [val] * placeholder_count )

                placeholder_count = 1
                is_first = False
                last_num = val


            else:
                """
                To handle after first iteration of below input string patterns
                    s = "_,_,_,60"
                    (OR)
                    s = "_,_,30,_,_,_,50,_,_"
                    (OR)
                    s = "80,_,_,_,_"
                    (OR)
                    s = "2_,_,30,_,_,_,50,_,_"
                """


                placeholder_count += 1

                val = (last_num + parsed_item) / placeholder_count

                if len(updated_items) > 0:
                    updated_items.pop()

                updated_items.extend( [val] * placeholder_count )

                placeholder_count, last_num = 1, val
    """
    To handle last operation of below input string patterns
        s = "_,_,30,_,_,_,50,_,_"
        (OR)
        s = "80,_,_,_,_"
    """
    if placeholder_count > 0:

        val = last_num / placeholder_count

        if len(updated_items) > 0:
            updated_items.pop()

        updated_items.extend( [val] * placeholder_count )
    
    """
    Join list items with comma separated
    """
    join_string = ','.join([str(item) for item in updated_items])
    
    return join_string
        
        
curve_smoothing(s)

'16.0,16.0,16.0,16.0,16.0'

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math as mt
dictionary1 = {
'F1S1': 0,
'F2S1': 0,
'F3S1': 0,
'F4S1': 0,
'F5S1': 0,
'F1S2': 0,
'F2S2': 0,
'F3S2': 0,
'F4S2': 0,
'F5S2': 0,
'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

dictionary2 = {
'S1': 0,
'S2': 0,
'S3': 0,
}


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
   for i in range(len(A)):
        for j in range(i+1,len(A)):
            c=1
            k = A[i][0] + A[i][1]
            dictionary1[k] = c

            if A[i][0]+A[i][1] == A[j][0]+A[j][1]:
                k = A[i][0] + A[i][1]
                c+=1
                dictionary1[k] = c
        dictionary2[A[i][1]] += 1
   k = A[len(A)-1][0] + A[len(A)-1][1]
   dictionary1[k] = 1

   return dictionary1,dictionary2     
        
    # print the output as per the instructions
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
d1,d2 = compute_conditional_probabilites(A)
print(d1,d2)

for key,value in dictionary1.items():
    if 'S1' in key:
        x=str(value/dictionary2['S1'])
        print('P(F={})'.format(key[:2])+'/S=={})= '.format(key[2:])+ x)
    if 'S2' in key:
        x=str(value/dictionary2['S2'])
        print('P(F={})'.format(key[:2])+'/S=={})= '.format(key[2:])+ x)
    if 'S3' in key:
        x=str(value/dictionary2['S3'])
        print('P(F={})'.format(key[:2])+'/S=={})= '.format(key[2:])+ x)
    



{'F1S1': 1, 'F2S1': 1, 'F3S1': 0, 'F4S1': 1, 'F5S1': 1, 'F1S2': 1, 'F2S2': 1, 'F3S2': 1, 'F4S2': 0, 'F5S2': 0, 'F1S3': 0, 'F2S3': 1, 'F3S3': 1, 'F4S3': 1, 'F5S3': 0} {'S1': 4, 'S2': 3, 'S3': 3}
P(F=F1)/S==S1)= 0.25
P(F=F2)/S==S1)= 0.25
P(F=F3)/S==S1)= 0.0
P(F=F4)/S==S1)= 0.25
P(F=F5)/S==S1)= 0.25
P(F=F1)/S==S2)= 0.3333333333333333
P(F=F2)/S==S2)= 0.3333333333333333
P(F=F3)/S==S2)= 0.3333333333333333
P(F=F4)/S==S2)= 0.0
P(F=F5)/S==S2)= 0.0
P(F=F1)/S==S3)= 0.0
P(F=F2)/S==S3)= 0.3333333333333333
P(F=F3)/S==S3)= 0.3333333333333333
P(F=F4)/S==S3)= 0.3333333333333333
P(F=F5)/S==S3)= 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    State1=S1.split(" ")
    State2=S2.split(" ")
    common=0
    for i in State1:
        for j in State2:
            if(i.lower()==j.lower()):
                common=common+1
    print(common)
    first=[]
    for i in State1:
        flag=0
        for j in State2:
            if(i.lower()==j.lower()):
                flag=1
        if(flag==0):
            first.append(i)
    second=[]
    for i in State2:
        flag=0
        for j in State1:
            if(i.lower()==j.lower()):
                flag=1
        if(flag==0):
            second.append(i)
    print(first)
    print(second)
    
    return 

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)


7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import  math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
  summ=0
  for i in range(len(A)):
      #x=math.log10(A[i][1])
      #y=math.log10((1-A[i][1]))
      summ=summ+(A[i][0]*math.log10(A[i][1]))+((1-A[i][0])*math.log10((1-A[i][1])))
      #print("i=",i," summ=",summ)
  result=(summ/len(A))*-1
  return result

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635


# New Section